"""End-to-end checks that validate the design the pipeline generated.

The pipeline's design job runs ``scripts/design_network.py`` (which gates
on a valid design) and uploads ``outputs/`` as an artifact; these tests
assert the structural guarantees of the design it produced.
"""

from __future__ import annotations

import collections
import json
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent


@pytest.fixture(name="design", scope="module")
def fixture_design() -> dict[str, Any]:
    """Load the design generated by the pipeline's design step."""
    text = (REPO_ROOT / "outputs" / "network_design.json").read_text(encoding="utf-8")
    payload: dict[str, Any] = json.loads(text)
    return payload


def core_names(design: dict[str, Any]) -> set[str]:
    """Test helper: build core names."""
    return {vertex["name"] for vertex in design["vertices"] if vertex["tier_role"] == "core"}


def aggregation_names(design: dict[str, Any]) -> set[str]:
    """Test helper: build aggregation names."""
    return {vertex["name"] for vertex in design["vertices"] if vertex["tier_role"] == "aggregation"}


def core_targets_by_aggregation(design: dict[str, Any]) -> dict[str, set[str]]:
    """Test helper: build core targets by aggregation."""
    targets: dict[str, set[str]] = collections.defaultdict(set)
    for use in design["path_uses"]:
        if use["purpose"] == "aggregation_to_core":
            targets[use["source_name"]].add(use["target_name"])
    return targets


def test_design_is_connected(design: dict[str, Any]) -> None:
    """Design is connected."""
    assert design["validation"]["connected"] is True


def test_aggregations_are_dual_homed_to_cores(design: dict[str, Any]) -> None:
    """Aggregations are dual homed to cores."""
    assert design["validation"]["aggregations_dual_homed_to_cores"] is True


def test_cores_form_full_mesh(design: dict[str, Any]) -> None:
    """Cores form full mesh."""
    assert design["validation"]["cores_full_mesh"] is True


def test_access_vertices_are_dual_homed(design: dict[str, Any]) -> None:
    """Access vertices are dual homed."""
    assert design["validation"]["access_vertices_with_two_aggregation_links"] is True


def test_core_tier_has_at_least_three_vertices(design: dict[str, Any]) -> None:
    """Core tier has at least the minimum three vertices."""
    assert len(core_names(design)) >= 3


def test_every_aggregation_reaches_two_distinct_cores(design: dict[str, Any]) -> None:
    """Every aggregation reaches two distinct cores."""
    targets = core_targets_by_aggregation(design)
    assert all(len(targets[name]) == 2 for name in aggregation_names(design))


def test_goodyear_is_not_an_aggregation(design: dict[str, Any]) -> None:
    """A single-homed leaf such as Goodyear is never selected as an aggregation."""
    assert "Goodyear, AZ" not in aggregation_names(design)
